services:
  app:
    build: 
      context: .
      args:
        DATABASE_URL: postgresql://postgres:password@db:5432/life-fundamentals
    ports:
      - "3000:5173"
      - "24678:24678"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/life-fundamentals
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    command: 
      - sh
      - -c
      - |
        echo 'Waiting for database...'
        sleep 5
        echo 'Running database migrations...'
        bun run db:migrate
        echo 'Starting development server...'
        bun run dev --host 0.0.0.0 --port 5173

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: life-fundamentals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
